--Execute on ais_replica DBO.PORTS
BEGIN
    SET NOCOUNT ON;
    SET QUERY_GOVERNOR_COST_LIMIT 0;

	SET IDENTITY_INSERT ais_replica.dbo.PORTS ON;

    MERGE ais_replica.dbo.PORTS AS A
    USING ais.dbo.PORTS AS B WITH (NOLOCK)
    ON A.PORT_ID = B.PORT_ID

    WHEN MATCHED AND (
        A.PORT_NAME <> B.PORT_NAME OR
		A.PORT_SIZE <> B.PORT_SIZE OR
        A.ALTNAME1 <> B.ALTNAME1 OR
        A.ALTNAME2 <> B.ALTNAME2 OR
        A.ALTNAME3 <> B.ALTNAME3 OR
        A.ALTNAME4 <> B.ALTNAME4 OR
        A.PORT_TYPE <> B.PORT_TYPE OR
        A.UNLOCODE <> B.UNLOCODE OR
        A.COUNTRY_CODE <> B.COUNTRY_CODE OR
        A.TIMEZONE <> B.TIMEZONE OR
        A.DST <> B.DST OR
        A.ENABLE_CALLS <> B.ENABLE_CALLS OR
        A.CONFIRMED <> B.CONFIRMED OR
        A.SW_X <> B.SW_X OR
        A.SW_Y <> B.SW_Y OR
        A.NE_X <> B.NE_X OR
        A.NE_Y <> B.NE_Y OR
        A.RELATED_ANCH_ID <> B.RELATED_ANCH_ID OR
        A.RELATED_PORT_ID <> B.RELATED_PORT_ID
    ) THEN
        UPDATE SET
            A.PORT_NAME = B.PORT_NAME,
			A.PORT_SIZE = B.PORT_SIZE,
            A.ALTNAME1 = B.ALTNAME1,
            A.ALTNAME2 = B.ALTNAME2,
            A.ALTNAME3 = B.ALTNAME3,
            A.ALTNAME4 = B.ALTNAME4,
            A.PORT_TYPE = B.PORT_TYPE,
            A.UNLOCODE = B.UNLOCODE,
            A.COUNTRY_CODE = B.COUNTRY_CODE,
            A.TIMEZONE = B.TIMEZONE,
            A.DST = B.DST,
            A.ENABLE_CALLS = B.ENABLE_CALLS,
            A.CONFIRMED = B.CONFIRMED,
            A.SW_X = B.SW_X,
            A.SW_Y = B.SW_Y,
            A.NE_X = B.NE_X,
            A.NE_Y = B.NE_Y,
            A.RELATED_ANCH_ID = B.RELATED_ANCH_ID,
            A.RELATED_PORT_ID = B.RELATED_PORT_ID

    WHEN NOT MATCHED BY TARGET THEN
        INSERT (
            PORT_ID, PORT_NAME, ALTNAME1, ALTNAME2, ALTNAME3, ALTNAME4,
            PORT_TYPE, UNLOCODE, COUNTRY_CODE, TIMEZONE, DST, ENABLE_CALLS,
            CONFIRMED, SW_X, SW_Y, NE_X, NE_Y, RELATED_ANCH_ID, RELATED_PORT_ID
        )
        VALUES (
            B.PORT_ID, B.PORT_NAME, B.ALTNAME1, B.ALTNAME2, B.ALTNAME3, B.ALTNAME4,
            B.PORT_TYPE, B.UNLOCODE, B.COUNTRY_CODE, B.TIMEZONE, B.DST, B.ENABLE_CALLS,
            B.CONFIRMED, B.SW_X, B.SW_Y, B.NE_X, B.NE_Y, B.RELATED_ANCH_ID, B.RELATED_PORT_ID
        )

    WHEN NOT MATCHED BY SOURCE THEN
        DELETE;
SET IDENTITY_INSERT ais_replica.dbo.PORTS OFF;
END