--Execute on AIS
BEGIN
	SET NOCOUNT ON;
	SET QUERY_GOVERNOR_COST_LIMIT 0

MERGE PORTS_CURRENT_TEMP A 
USING PORTS_CURRENT B WITH(NOLOCK) 
ON A.PORT_ID=B.PORT_ID
WHEN MATCHED AND (A.SHIPCOUNT<>B.SHIPCOUNT OR A.EXPECTEDCOUNT<>B.EXPECTEDCOUNT OR A.COVERAGE<>B.COVERAGE OR A.CURRENT_OFFSET IS NULL OR A.CURRENT_OFFSET<>B.CURRENT_OFFSET) THEN
  UPDATE
  SET A.SHIPCOUNT=B.SHIPCOUNT, A.DEPARTCOUNT=B.DEPARTCOUNT, A.ARRIVECOUNT=B.ARRIVECOUNT, A.EXPECTEDCOUNT=B.EXPECTEDCOUNT, A.COUNT_PHOTOS=B.COUNT_PHOTOS, A.COVERAGE=B.COVERAGE, 
  A.[CURRENT_TIME]=B.[CURRENT_TIME], A.CURRENT_OFFSET=B.CURRENT_OFFSET, A.PORT_SIZE=B.PORT_SIZE
WHEN NOT MATCHED BY TARGET THEN
  INSERT (SHIPCOUNT, PORT_ID, PORT_NAME, SW_X, SW_Y, NE_X, NE_Y, CENTERX, CENTERY, DEPARTCOUNT, ARRIVECOUNT, EXPECTEDCOUNT, ZOOM, 
                      COUNT_PHOTOS, COUNTRY_CODE, COUNTRY, ALTNAME1, ALTNAME2, ALTNAME3, ALTNAME4, PORT_TYPE, ENABLE_CALLS, COVERAGE, UNLOCODE,
					  [CURRENT_TIME], CURRENT_OFFSET, PORT_SIZE, AREA_ID, AREA_CODE, RELATED_ANCH_ID, RELATED_ANCH_NAME, RELATED_PORT_ID, RELATED_PORT_NAME)
  VALUES (B.SHIPCOUNT, B.PORT_ID, B.PORT_NAME, B.SW_X, B.SW_Y, B.NE_X, B.NE_Y, B.CENTERX, B.CENTERY, B.DEPARTCOUNT, B.ARRIVECOUNT, B.EXPECTEDCOUNT, B.ZOOM, 
                      B.COUNT_PHOTOS, B.COUNTRY_CODE, B.COUNTRY, B.ALTNAME1, B.ALTNAME2, B.ALTNAME3, B.ALTNAME4, B.PORT_TYPE, B.ENABLE_CALLS, B.COVERAGE, B.UNLOCODE,
					  B.[CURRENT_TIME], B.CURRENT_OFFSET, B.PORT_SIZE, AREA_ID, AREA_CODE, RELATED_ANCH_ID, RELATED_ANCH_NAME, RELATED_PORT_ID, RELATED_PORT_NAME)
WHEN NOT MATCHED BY SOURCE THEN
  DELETE;


--Full update and STAT_PORTS -- run twice only every 24 hours
--if datepart(hour,getutcdate())=3 AND datepart(MINUTE,getutcdate())<11
begin
	--Disable Indexes
	ALTER INDEX ALTNAMES ON PORTS_CURRENT_TEMP DISABLE
	ALTER INDEX NAME ON PORTS_CURRENT_TEMP DISABLE

	TRUNCATE TABLE PORTS_CURRENT_TEMP
	INSERT INTO PORTS_CURRENT_TEMP WITH (TABLOCK) (SHIPCOUNT, PORT_ID, PORT_NAME, SW_X, SW_Y, NE_X, NE_Y, CENTERX, CENTERY, DEPARTCOUNT, ARRIVECOUNT, EXPECTEDCOUNT, ZOOM
		,COUNT_PHOTOS, COUNTRY_CODE, COUNTRY, ALTNAME1, ALTNAME2, ALTNAME3, ALTNAME4, PORT_TYPE, ENABLE_CALLS, COVERAGE, UNLOCODE
		,[CURRENT_TIME], CURRENT_OFFSET, PORT_SIZE, AREA_ID, AREA_CODE, RELATED_ANCH_ID, RELATED_ANCH_NAME, RELATED_PORT_ID, RELATED_PORT_NAME, AREA_NAME, AREA_CODE_NAME)
	(SELECT SHIPCOUNT, PORT_ID, PORT_NAME, SW_X, SW_Y, NE_X, NE_Y, CENTERX, CENTERY, DEPARTCOUNT, ARRIVECOUNT, EXPECTEDCOUNT, ZOOM
		,COUNT_PHOTOS, COUNTRY_CODE, COUNTRY, ALTNAME1, ALTNAME2, ALTNAME3, ALTNAME4, PORT_TYPE, ENABLE_CALLS, COVERAGE, UNLOCODE 
		,[CURRENT_TIME], CURRENT_OFFSET, PORT_SIZE, AREA_ID, AREA_CODE, RELATED_ANCH_ID, RELATED_ANCH_NAME, RELATED_PORT_ID, RELATED_PORT_NAME, AREA_NAME, AREA_CODE_NAME
		FROM PORTS_CURRENT WITH(NOLOCK))
					  
	--Enable Indexes
	ALTER INDEX ALTNAMES ON PORTS_CURRENT_TEMP REBUILD
	ALTER INDEX NAME ON PORTS_CURRENT_TEMP REBUILD

	--Port Metrics - Max/Avg Length
	UPDATE P
	SET P.MAX_LENGTH = B.MAX_LENGTH, P.AVG_LENGTH = B.AVG_LENGTH
	FROM PORTS_CURRENT_TEMP P INNER JOIN
		(SELECT PORT_ID, CEILING(MAX(LENGTH)) AS MAX_LENGTH, CEILING(AVG(LENGTH)) AS AVG_LENGTH
		FROM
			(SELECT DISTINCT TOP 99.9 PERCENT VSB.LENGTH, PM.PORT_ID, PM.SHIP_ID, VSB.INVALID_DIMENSIONS, PM.DRAUGHT, VSB.WIDTH
			FROM PORT_MOVES PM
			INNER JOIN V_SHIP_BATCH VSB ON VSB.SHIP_ID = PM.SHIP_ID
			WHERE PM.TIMESTAMP>GETUTCDATE()-365 AND MOVE_TYPE = 0 AND INTRANSIT = 0 AND SHIPTYPE NOT IN (31,32,50,52,53,56,57,0,1,9)
			AND VSB.INVALID_DIMENSIONS=0 AND VSB.INVALID_MMSI=0
			ORDER BY LENGTH ASC) A
		GROUP BY PORT_ID) B
	ON P.PORT_ID = B.PORT_ID

	--Port Metrics - Max Draught and Max DWT
	UPDATE P
	SET P.MAX_DRAUGHT = C.MAX_DRAUGHT, P.MAX_DWT = C.MAX_DWT
	FROM PORTS_CURRENT_TEMP P INNER JOIN
		(SELECT B.PORT_ID, PORT_NAME, VAR(DRAUGHT) AS VAR_DRAUGHT, COUNT(*) AS OBSERVATIONS, MAX(DRAUGHT) AS MAX_DRAUGHT, AVG(DRAUGHT) AS AVG_DRAUGHT, STDEV(DRAUGHT) AS STDEV_DRAUGHT, MAX(DWT) AS MAX_DWT
		FROM
			(SELECT PORT_ID, DRAUGHT, DWT, ROW_NUMBER() OVER (PARTITION BY PORT_ID ORDER BY DRAUGHT DESC) AS ROWNUMBER
			FROM 
				(SELECT DISTINCT VSB.LENGTH, PM.PORT_ID, PM.SHIP_ID, VSB.INVALID_DIMENSIONS, PM.DRAUGHT, VSB.DWT, VSB.WIDTH --distinct Vessels/Draughts - Not all port calls
				FROM PORT_MOVES PM
				INNER JOIN V_SHIP_BATCH VSB ON VSB.SHIP_ID = PM.SHIP_ID
				WHERE PM.TIMESTAMP>GETUTCDATE()-365 AND MOVE_TYPE = 0 AND INTRANSIT = 0 AND SHIPTYPE NOT IN (31,32,50,52,53,56,57,0,1,9)
				AND PM.DRAUGHT > 15 AND PM.DRAUGHT < VSB.LENGTH * 10 / 4 AND PM.DRAUGHT < VSB.WIDTH * 10 / 2 AND VSB.LENGTH/PM.DRAUGHT/PM.DRAUGHT*100 > 1.0 -- Draught remove possible invalid values, platforms etc.
				AND VSB.INVALID_DIMENSIONS=0 AND VSB.INVALID_MMSI=0
				--ORDER BY DRAUGHT DESC
				) A
			)B
		INNER JOIN PORTS ON PORTS.PORT_ID = B.PORT_ID
		WHERE ROWNUMBER > 4  --Exclude 5 top values as possible outliers
		GROUP BY B.PORT_ID, PORT_NAME) C
	ON P.PORT_ID = C.PORT_ID

	--List of top 5 shiptypes
	UPDATE P
	SET P.SHIPTYPE_LIST = B.SHIPTYPE_LIST
	FROM PORTS_CURRENT_TEMP P INNER JOIN
		(SELECT PORT_ID, STRING_AGG(TYPE_NAME + ' (' + PERCENTAGE + '%)', ', ') AS SHIPTYPE_LIST 
		FROM
			(SELECT PM.PORT_ID, CONVERT(VARCHAR, COUNT(DISTINCT PM.SHIP_ID)*100/TOTAL_COUNT) AS PERCENTAGE, TYPE_NAME, TOTAL_COUNT
				,ROW_NUMBER() OVER (PARTITION BY PM.PORT_ID ORDER BY COUNT(DISTINCT PM.SHIP_ID) DESC) AS RN
			FROM PORT_MOVES PM
			INNER JOIN V_SHIP_BATCH VSB ON VSB.SHIP_ID = PM.SHIP_ID
			CROSS APPLY (SELECT COUNT(DISTINCT PM1.SHIP_ID) AS TOTAL_COUNT 
				FROM PORT_MOVES PM1 
				INNER JOIN V_SHIP_BATCH VSB1 ON VSB1.SHIP_ID = PM1.SHIP_ID
				WHERE PM1.PORT_ID = PM.PORT_ID AND PM1.TIMESTAMP>GETUTCDATE()-90
				AND PM1.MOVE_TYPE = 0 AND PM1.INTRANSIT = 0 AND VSB1.SHIPTYPE NOT IN (31,32,50,52,53,56,57,0,1,9)
				) AS A
			WHERE PM.TIMESTAMP>GETUTCDATE()-90 AND MOVE_TYPE = 0 AND INTRANSIT = 0 AND SHIPTYPE NOT IN (31,32,50,52,53,56,57,0,1,9)
			GROUP BY TYPE_NAME, TOTAL_COUNT, PM.PORT_ID
			HAVING COUNT(*) > 5) A
		WHERE RN <= 5
		GROUP BY PORT_ID) B
	ON P.PORT_ID = B.PORT_ID

	--Stats
	TRUNCATE TABLE STAT_PORTS_BATCH_2
	INSERT INTO STAT_PORTS_BATCH_2 WITH (TABLOCK) (PORT_ID, TIMESTAMP, [UNSPECIFIED], [CONTAINER SHIPS], [DRY BREAKBULK], [DRY BULK], [FISHING],
        [LNG CARRIERS], [LPG CARRIERS], [OFFSHORE/RIGS], [OTHER MARKETS], [PASSENGER SHIPS],
        [PLEASURE CRAFT], [RO/RO], [SUPPORTING VESSELS], [WET BULK], PORT_NAME)
	(SELECT PORT_ID, TIMESTAMP, [UNSPECIFIED], [CONTAINER SHIPS], [DRY BREAKBULK], [DRY BULK], [FISHING],
        [LNG CARRIERS], [LPG CARRIERS], [OFFSHORE/RIGS], [OTHER MARKETS], [PASSENGER SHIPS],
        [PLEASURE CRAFT], [RO/RO], [SUPPORTING VESSELS], [WET BULK], PORT_NAME FROM STAT_PORTS_2 WITH(NOLOCK))
end

BEGIN TRAN
exec sp_rename 'PORTS_CURRENT_BATCH', 'PORTS_CURRENT_TEMP1'
exec sp_rename 'PORTS_CURRENT_TEMP', 'PORTS_CURRENT_BATCH'
exec sp_rename 'PORTS_CURRENT_TEMP1', 'PORTS_CURRENT_TEMP'
COMMIT


--Moving ports - update coordinates of their polygon - remove polygon if they are within other port -- hourly run
--if(datepart(minute, getutcdate()) between 0 and 5)
begin
	--Insert all new Floating Storage/Production units
	INSERT INTO PORTS (MOVING_SHIP_ID, PORT_NAME, PORT_TYPE, CONFIRMED)
	(SELECT SHIP_ID, LEFT(SHIPNAME, 20), 'T', 1 
	FROM V_SHIP_BATCH S
	WHERE GT_SHIPTYPE=56 
	AND TERRSAT_TIMESTAMP > GETUTCDATE()-30
	AND NOT EXISTS (SELECT 1 FROM PORTS WHERE MOVING_SHIP_ID = S.SHIP_ID))

	--Update geometries and related details of all moving ports
	UPDATE P
	SET P.POLYGON = (CASE WHEN S.PORT_ID IS NULL THEN geography::Point(S.TERRSAT_LAT, S.TERRSAT_LON, 4326).STBuffer(600).Reduce(100) ELSE NULL END)
	,P.SW_X=S.TERRSAT_LON, P.SW_Y=S.TERRSAT_LAT, P.NE_X=S.TERRSAT_LON, P.NE_Y=S.TERRSAT_LAT
	,P.COUNTRY_CODE=S.CODE2
	,P.ENABLE_CALLS=(CASE WHEN S.PORT_ID IS NULL THEN 1 ELSE 0 END)
	,P.TIMEZONE = S.TIMEZONE, P.DST=0
	,AREA_CODE = (SELECT TOP 1 AREA_CODE FROM AREAS WITH(INDEX(POLYGON)) WHERE AREAS.POLYGON.STIntersects(P.POLYGON)=1 AND AREA_CODE IS NOT NULL ORDER BY ZOOM DESC)
	,AREA_ID = (SELECT TOP 1 AREA_ID FROM AREAS WITH(INDEX(POLYGON)) WHERE AREAS.POLYGON.STIntersects(P.POLYGON)=1 ORDER BY ZOOM DESC)
	FROM PORTS P INNER JOIN V_SHIP_BATCH S ON P.MOVING_SHIP_ID=S.SHIP_ID
	WHERE S.GT_SHIPTYPE = 56 AND S.STATUS = '' AND S.TERRSAT_LAT IS NOT NULL AND S.TERRSAT_LON IS NOT NULL
end

-- Disable port calls for non-existent/inactive moving ports
UPDATE PORTS SET ENABLE_CALLS = 0, POLYGON = NULL, NE_X = NULL, NE_Y = NULL
WHERE PORT_ID IN (
  SELECT PORT_ID FROM PORTS P WITH (NOLOCK)
  WHERE MOVING_SHIP_ID IS NOT NULL
    AND ( (NOT EXISTS (SELECT 1 FROM LAST_SEEN_SHIP WITH (NOLOCK)  WHERE P.MOVING_SHIP_ID = SHIP_ID)) 
	 OR ((SELECT STATUS FROM V_SHIP_BATCH WITH (NOLOCK) WHERE P.MOVING_SHIP_ID = SHIP_ID)<>'')
	 OR ((SELECT GT_SHIPTYPE FROM V_SHIP_BATCH WITH (NOLOCK) WHERE P.MOVING_SHIP_ID = SHIP_ID)<>56)
	)
)


END

GO