--Execute on ais_replica  PORT_CURRENT_BATCH
BEGIN
    SET NOCOUNT ON;
    SET QUERY_GOVERNOR_COST_LIMIT 0;

    MERGE ais_replica.dbo.PORTS_CURRENT_BATCH AS A
    USING ais.dbo.PORTS_CURRENT_BATCH AS B WITH (NOLOCK)
    ON A.PORT_ID = B.PORT_ID

    WHEN MATCHED AND (
        A.SHIPCOUNT <> B.SHIPCOUNT OR
        A.PORT_NAME <> B.PORT_NAME OR
        A.SW_X <> B.SW_X OR
        A.SW_Y <> B.SW_Y OR
        A.NE_X <> B.NE_X OR
        A.NE_Y <> B.NE_Y OR
        A.CENTERX <> B.CENTERX OR
        A.CENTERY <> B.CENTERY OR
        A.DEPARTCOUNT <> B.DEPARTCOUNT OR
        A.ARRIVECOUNT <> B.ARRIVECOUNT OR
        A.EXPECTEDCOUNT <> B.EXPECTEDCOUNT OR
        A.ZOOM <> B.ZOOM OR
        A.COUNT_PHOTOS <> B.COUNT_PHOTOS OR
        A.COUNTRY_CODE <> B.COUNTRY_CODE OR
        A.COUNTRY <> B.COUNTRY OR
        A.ALTNAME1 <> B.ALTNAME1 OR
        A.ALTNAME2 <> B.ALTNAME2 OR
        A.ALTNAME3 <> B.ALTNAME3 OR
        A.ALTNAME4 <> B.ALTNAME4 OR
        A.PORT_TYPE <> B.PORT_TYPE OR
        A.ENABLE_CALLS <> B.ENABLE_CALLS OR
        A.COVERAGE <> B.COVERAGE OR
        A.UNLOCODE <> B.UNLOCODE OR
        A.[CURRENT_TIME] <> B.[CURRENT_TIME] OR
        A.CURRENT_OFFSET <> B.CURRENT_OFFSET OR
        A.PORT_SIZE <> B.PORT_SIZE OR
        A.AREA_ID <> B.AREA_ID OR
        A.AREA_CODE <> B.AREA_CODE OR
        A.RELATED_ANCH_ID <> B.RELATED_ANCH_ID OR
        A.RELATED_ANCH_NAME <> B.RELATED_ANCH_NAME OR
        A.RELATED_PORT_ID <> B.RELATED_PORT_ID OR
        A.RELATED_PORT_NAME <> B.RELATED_PORT_NAME OR
        A.AREA_NAME <> B.AREA_NAME OR
        A.AREA_CODE_NAME <> B.AREA_CODE_NAME OR
        A.MAX_LENGTH <> B.MAX_LENGTH OR
        A.AVG_LENGTH <> B.AVG_LENGTH OR
        A.MAX_DRAUGHT <> B.MAX_DRAUGHT OR
        A.MAX_DWT <> B.MAX_DWT OR
        A.SHIPTYPE_LIST <> B.SHIPTYPE_LIST
    ) THEN
        UPDATE SET
            A.SHIPCOUNT = B.SHIPCOUNT,
            A.PORT_NAME = B.PORT_NAME,
            A.SW_X = B.SW_X,
            A.SW_Y = B.SW_Y,
            A.NE_X = B.NE_X,
            A.NE_Y = B.NE_Y,
            A.CENTERX = B.CENTERX,
            A.CENTERY = B.CENTERY,
            A.DEPARTCOUNT = B.DEPARTCOUNT,
            A.ARRIVECOUNT = B.ARRIVECOUNT,
            A.EXPECTEDCOUNT = B.EXPECTEDCOUNT,
            A.ZOOM = B.ZOOM,
            A.COUNT_PHOTOS = B.COUNT_PHOTOS,
            A.COUNTRY_CODE = B.COUNTRY_CODE,
            A.COUNTRY = B.COUNTRY,
            A.ALTNAME1 = B.ALTNAME1,
            A.ALTNAME2 = B.ALTNAME2,
            A.ALTNAME3 = B.ALTNAME3,
            A.ALTNAME4 = B.ALTNAME4,
            A.PORT_TYPE = B.PORT_TYPE,
            A.ENABLE_CALLS = B.ENABLE_CALLS,
            A.COVERAGE = B.COVERAGE,
            A.UNLOCODE = B.UNLOCODE,
            A.[CURRENT_TIME] = B.[CURRENT_TIME],
            A.CURRENT_OFFSET = B.CURRENT_OFFSET,
            A.PORT_SIZE = B.PORT_SIZE,
            A.AREA_ID = B.AREA_ID,
            A.AREA_CODE = B.AREA_CODE,
            A.RELATED_ANCH_ID = B.RELATED_ANCH_ID,
            A.RELATED_ANCH_NAME = B.RELATED_ANCH_NAME,
            A.RELATED_PORT_ID = B.RELATED_PORT_ID,
            A.RELATED_PORT_NAME = B.RELATED_PORT_NAME,
            A.AREA_NAME = B.AREA_NAME,
            A.AREA_CODE_NAME = B.AREA_CODE_NAME,
            A.MAX_LENGTH = B.MAX_LENGTH,
            A.AVG_LENGTH = B.AVG_LENGTH,
            A.MAX_DRAUGHT = B.MAX_DRAUGHT,
            A.MAX_DWT = B.MAX_DWT,
            A.SHIPTYPE_LIST = B.SHIPTYPE_LIST

    WHEN NOT MATCHED BY TARGET THEN
        INSERT (
            SHIPCOUNT, PORT_ID, PORT_NAME, SW_X, SW_Y, NE_X, NE_Y, CENTERX, CENTERY,
            DEPARTCOUNT, ARRIVECOUNT, EXPECTEDCOUNT, ZOOM, COUNT_PHOTOS, COUNTRY_CODE,
            COUNTRY, ALTNAME1, ALTNAME2, ALTNAME3, ALTNAME4, PORT_TYPE, ENABLE_CALLS,
            COVERAGE, UNLOCODE, [CURRENT_TIME], CURRENT_OFFSET, PORT_SIZE,
            AREA_ID, AREA_CODE, RELATED_ANCH_ID, RELATED_ANCH_NAME,
            RELATED_PORT_ID, RELATED_PORT_NAME, AREA_NAME, AREA_CODE_NAME,
            MAX_LENGTH, AVG_LENGTH, MAX_DRAUGHT, MAX_DWT, SHIPTYPE_LIST
        )
        VALUES (
            B.SHIPCOUNT, B.PORT_ID, B.PORT_NAME, B.SW_X, B.SW_Y, B.NE_X, B.NE_Y, B.CENTERX, B.CENTERY,
            B.DEPARTCOUNT, B.ARRIVECOUNT, B.EXPECTEDCOUNT, B.ZOOM, B.COUNT_PHOTOS, B.COUNTRY_CODE,
            B.COUNTRY, B.ALTNAME1, B.ALTNAME2, B.ALTNAME3, B.ALTNAME4, B.PORT_TYPE, B.ENABLE_CALLS,
            B.COVERAGE, B.UNLOCODE, B.[CURRENT_TIME], B.CURRENT_OFFSET, B.PORT_SIZE,
            B.AREA_ID, B.AREA_CODE, B.RELATED_ANCH_ID, B.RELATED_ANCH_NAME,
            B.RELATED_PORT_ID, B.RELATED_PORT_NAME, B.AREA_NAME, B.AREA_CODE_NAME,
            B.MAX_LENGTH, B.AVG_LENGTH, B.MAX_DRAUGHT, B.MAX_DWT, B.SHIPTYPE_LIST
        )

    WHEN NOT MATCHED BY SOURCE THEN
        DELETE;
END