BEGIN
SET NOCOUNT ON;

declare @syn_object as varchar(50)
set @syn_object = (SELECT TOP 1 PARSENAME(base_object_name,1) AS objectName 
FROM sys.synonyms WHERE name='V_TERMINAL_DETAILS_TERMINALS_BATCH')

DECLARE @DetErrorMess VARCHAR(MAX), @ErrorSeverity  tinyint, @ErrorState tinyint;

BEGIN TRY
	BEGIN TRAN;
 

WITH 

DOCKED AS
(
SELECT PT.TERMINAL_ID,COUNT(VSB.SHIP_ID) AS NOW_DOCKED
FROM PORT_TERMINALS AS PT WITH(NOLOCK) LEFT JOIN V_SHIP_BATCH AS VSB WITH (NOLOCK) ON PT.TERMINAL_ID=VSB.TERMINAL_ID
WHERE VSB.TERMINAL_ID IS NOT NULL 
AND (VSB.LAST_POS > DATEADD(DAY, -90, GETUTCDATE()) OR VSB.SAT_LAST_POS> DATEADD(DAY, -90, GETUTCDATE()) ) --active vessels: last received position not more than 90 days ago
AND VSB.COMFLEET_GROUPEDTYPE IN ('CONTAINER SHIPS', 'DRY BREAKBULK', 'DRY BULK', 'LNG CARRIERS', 'LPG CARRIERS', 'PASSENGER SHIPS', 'RO/RO', 'WET BULK')--commercial only
GROUP BY PT.TERMINAL_ID
)

,
SHIPTYPE AS 
(
SELECT TERMINAL_ID, STRING_AGG(TYPE_NAME + ' (' + PERCENTAGE + '%)', ', ') AS SHIPTYPE_LIST, TOTAL_COUNT 
		FROM
			(

SELECT PB.TERMINAL_ID,A.TOTAL_COUNT,VSB.TYPE_NAME,CONVERT(VARCHAR, COUNT(DISTINCT BM.SHIP_ID)*100/TOTAL_COUNT) AS PERCENTAGE,
		ROW_NUMBER() OVER (PARTITION BY PB.terminal_id ORDER BY COUNT(DISTINCT BM.SHIP_ID) DESC) AS RN
FROM PORT_BERTHS AS PB WITH(NOLOCK) INNER JOIN AIS_EVENTS.DBO.BERTH_MOVES AS BM WITH(NOLOCK) ON PB.BERTH_ID=BM.BERTH_ID
INNER JOIN V_SHIP_BATCH AS VSB WITH(NOLOCK) ON VSB.SHIP_ID=BM.SHIP_ID
CROSS APPLY (SELECT COUNT(DISTINCT BM1.SHIP_ID) AS TOTAL_COUNT
FROM 	
AIS_EVENTS.DBO.BERTH_MOVES AS BM1 WITH(NOLOCK)
INNER JOIN AIS.DBO.PORT_BERTHS AS PB1 WITH(NOLOCK) ON PB1.BERTH_ID=BM1.BERTH_ID
WHERE PB1.TERMINAL_ID = PB.TERMINAL_ID AND PB1.TERMINAL_ID IS NOT NULL AND BM1.TIMESTAMP>GETUTCDATE()-90
AND BM1.MOVE_TYPE = 0  AND BM1.SHIP_ID IN (SELECT SHIP_ID FROM V_SHIP_BATCH WITH(NOLOCK) WHERE COMFLEET_GROUPEDTYPE IN ('CONTAINER SHIPS', 'DRY BREAKBULK', 'DRY BULK', 'LNG CARRIERS', 'LPG CARRIERS', 'PASSENGER SHIPS', 'RO/RO', 'WET BULK')--commercial only
)
)AS A
WHERE  BM.TIMESTAMP>GETUTCDATE()-90 AND MOVE_TYPE = 0 
			AND COMFLEET_GROUPEDTYPE IN ('CONTAINER SHIPS', 'DRY BREAKBULK', 'DRY BULK', 'LNG CARRIERS', 'LPG CARRIERS', 'PASSENGER SHIPS', 'RO/RO', 'WET BULK')--commercial only
            AND PB.TERMINAL_ID IS NOT NULL

			GROUP BY TYPE_NAME, TOTAL_COUNT, PB.terminal_id

			) AS A
		WHERE RN <= 5
		GROUP BY TERMINAL_ID, TOTAL_COUNT)

SELECT PT.TERMINAL_ID, PT.TERMINAL_NAME, PT.PORT_ID,DOCKED.NOW_DOCKED,SHIPTYPE.SHIPTYPE_LIST,SHIPTYPE.TOTAL_COUNT
into #temp_V_TERMINAL_DETAILS_TERMINALS_BATCH

FROM PORT_TERMINALS AS PT WITH(NOLOCK) LEFT JOIN DOCKED ON PT.TERMINAL_ID=DOCKED.TERMINAL_ID 
LEFT JOIN  SHIPTYPE ON PT.TERMINAL_ID=SHIPTYPE.TERMINAL_ID
WHERE PT.TERMINAL_NAME IS NOT NULL AND PT.TERMINAL_NAME NOT LIKE '' AND PT.TERMINAL_NAME NOT LIKE '-' --exclude terminals without name

set @DetErrorMess=convert(varchar(400),@@ROWCOUNT);
		PRINT ' **** '+@@SERVERNAME+ '.'+DB_NAME()+'['+CONVERT(VARCHAR(19), GETDATE(),126)+']';
		PRINT ' ** V_TERMINAL_DETAILS_TERMINALS_BATCH : (Create #temp tb: ##temp_V_TERMINAL_DETAILS_TERMINALS_BATCH) row(s) affected: ' + @DetErrorMess;	

if(@syn_object='V_TERMINAL_DETAILS_TERMINALS_BATCH1') 
			begin
				BEGIN TRAN 
					
					TRUNCATE TABLE [V_TERMINAL_DETAILS_TERMINALS_BATCH2]; 
					
					INSERT INTO [V_TERMINAL_DETAILS_TERMINALS_BATCH2] 
					(TERMINAL_ID,TERMINAL_NAME,PORT_ID,NOW_DOCKED,SHIPTYPE_LIST,TOTAL_COUNT)
					(SELECT TERMINAL_ID,TERMINAL_NAME,PORT_ID,NOW_DOCKED,SHIPTYPE_LIST,TOTAL_COUNT
					FROM #temp_V_TERMINAL_DETAILS_TERMINALS_BATCH)

if OBJECT_ID('[shad].V_TERMINAL_DETAILS_TERMINALS_BATCH') IS NOT NULL
					begin
						DROP SYNONYM [shad].[V_TERMINAL_DETAILS_TERMINALS_BATCH];
					end
					CREATE SYNONYM [shad].[V_TERMINAL_DETAILS_TERMINALS_BATCH] FOR [dbo].[V_TERMINAL_DETAILS_TERMINALS_BATCH2];

					ALTER SCHEMA [fk] TRANSFER [dbo].[V_TERMINAL_DETAILS_TERMINALS_BATCH];
					ALTER SCHEMA [dbo] TRANSFER [shad].[V_TERMINAL_DETAILS_TERMINALS_BATCH];
					ALTER SCHEMA [shad] TRANSFER [fk].[V_TERMINAL_DETAILS_TERMINALS_BATCH];

				COMMIT TRAN;  
end
else if(@syn_object='V_TERMINAL_DETAILS_TERMINALS_BATCH2')
			begin
				BEGIN TRAN
					
					TRUNCATE TABLE [V_TERMINAL_DETAILS_TERMINALS_BATCH1];

					INSERT INTO [V_TERMINAL_DETAILS_TERMINALS_BATCH1] 
					(TERMINAL_ID,TERMINAL_NAME,PORT_ID,NOW_DOCKED,SHIPTYPE_LIST,TOTAL_COUNT)
					(SELECT TERMINAL_ID,TERMINAL_NAME,PORT_ID,NOW_DOCKED,SHIPTYPE_LIST,TOTAL_COUNT
					FROM #temp_V_TERMINAL_DETAILS_TERMINALS_BATCH)

					if OBJECT_ID('[shad].V_TERMINAL_DETAILS_TERMINALS_BATCH') IS NOT NULL
					begin
						DROP SYNONYM [shad].[V_TERMINAL_DETAILS_TERMINALS_BATCH];
					end
					CREATE SYNONYM [shad].[V_TERMINAL_DETAILS_TERMINALS_BATCH] FOR [dbo].[V_TERMINAL_DETAILS_TERMINALS_BATCH1];

					ALTER SCHEMA [fk] TRANSFER [dbo].[V_TERMINAL_DETAILS_TERMINALS_BATCH];
					ALTER SCHEMA [dbo] TRANSFER [shad].[V_TERMINAL_DETAILS_TERMINALS_BATCH];
					ALTER SCHEMA [shad] TRANSFER [fk].[V_TERMINAL_DETAILS_TERMINALS_BATCH];
				COMMIT TRAN;  
			end
			else if(@syn_object is null)
			begin
				CREATE SYNONYM [dbo].[V_TERMINAL_DETAILS_TERMINALS_BATCH] FOR [dbo].[V_TERMINAL_DETAILS_TERMINALS_BATCH1]  
				CREATE SYNONYM [shad].[V_TERMINAL_DETAILS_TERMINALS_BATCH] FOR [dbo].[V_TERMINAL_DETAILS_TERMINALS_BATCH2]  
			end
		
	COMMIT TRAN;	
	END TRY

BEGIN CATCH
	--
	SET @ErrorSeverity = ERROR_SEVERITY()
	SET @ErrorState    = ERROR_STATE()
	SET @DetErrorMess =  ' **** ERROR_NUMBER ' +        
	  CAST(ERROR_NUMBER() AS VARCHAR) + ' : '+
	  CAST(@ErrorSeverity AS VARCHAR) + ' : ' +
	  CAST(@ErrorState AS VARCHAR) + ' : ' +
	  ERROR_PROCEDURE() + ' : ' +
	  ERROR_MESSAGE() + ' : ERROR_LINE ' +
	  CAST(ERROR_LINE() AS VARCHAR);

	-- Test XACT_STATE for 1 or -1. XACT_STATE = 0 means there is no transaction and a commit or rollback operation would generate an error.
	IF (XACT_STATE()) <> 0
	BEGIN
		--D.p: 
			PRINT '(XACT_STATE) before ROLLBACK: ' + CAST(XACT_STATE() AS VARCHAR(10)); 
			ROLLBACK TRAN;
	END;
	-- detailed error message....return
	PRINT ' **** '+@@SERVERNAME+ '.'+DB_NAME()+'['+CONVERT(VARCHAR(19), GETDATE(),126)+']';
	RAISERROR(@DetErrorMess, @ErrorSeverity, @ErrorState);
	RETURN;
END CATCH;

PRINT ' **** '+@@SERVERNAME+ '.'+DB_NAME()+'['+CONVERT(VARCHAR(19), GETDATE(),126)+']';
PRINT ' ** V_TERMINAL_DETAILS_TERMINALS_BATCH :  Drop temp tb: #temp_V_TERMINAL_DETAILS_TERMINALS_BATCH';
DROP TABLE #temp_V_TERMINAL_DETAILS_TERMINALS_BATCH;
	
END
GO